pipeline{
    
    agent any

    tools {
        maven 'Maven 3.6.1' 
    }
    
    stages{
        stage(one){
          steps{
              echo 'Compiling worker app'
              dir('worker'){
                sh 'mvn compile'
              }
          }
      	}
        stage(two){
            steps{
                echo 'The Great One'
                sleep 7
            }
        }
        stage(three){
            steps{
                echo 'The Rock'
                sleep 3
            }
        }
    }
    
    post { 
        always { 
            echo 'I will always say Hello again!'
            sleep 8
        }
    }
    
    
}
