pipeline{
    
    agent any

    tools {
        maven 'Maven 3.6.1' 
    }
    
    stages{
        stage(build){
            steps{
                echo 'Building worker app'
                dir('worker')
		sh 'mvn compile'
            }
        }
        stage(test){
            steps{
                echo 'Testing worker build'
                sh 'mvn clean test'
            }
        }
        stage(package){
            steps{
                echo 'Creating Package'
                sh 'mvn package -DskipTests'
            }
        }
    }
    
    post { 
        always { 
            echo 'I will always say Hello again!'
            sleep 8
        }
    }
    
    
}
